import React from 'react';

export default function PrivacyPolicy() {
    return (
        <div className="flex text-center flex-col mt-2">
            <div className="mb-4">
                <h1 className="text-4xl mb-4 font-extrabold">Terms & Conditions</h1>
                <p className="text">This website is owned and operated by Chiranabin (“Chiranabin”, “we,” “us” or “our”). Chiranabin provides this website, including all information, software and services available from this website, to you, the user, conditioned upon your acceptance of all the terms, conditions, policies and notices described herein. Your use of the website constitutes your agreement to all such terms, conditions, policies and notices.</p>
            </div>
            <div className="mb-4">
                <header className="text-lg font-bold">Your Use of the Website</header>
                <p className="text">This website is for your personal and non-commercial use. As a condition to your use of the website, you warrant to Chiranabin that you will not use the website for any purpose that is unlawful or prohibited by these General Terms and Conditions.</p>
            </div>
            <div className="mb-4">
                <header className="text-lg font-bold">Privacy Policy</header>
                <p className="text">You explicitly consent to the collection, hosting, use, disclosure and other processing or handling of information as described in the Chiranabin’s Privacy Policy located at http://www.chiranabin.org.in/ as such policy may be amended by Chiranabin in its sole discretion from time to time.</p>
            </div>
            <div className="mb-4">
                <header className="text-lg font-bold">Accuracy, Completeness and Timeliness of Information on the Website</header>
                <p className="text">We strive to provide accurate information on our website. We are not responsible, however, if information we make available on this website is not accurate, complete or current. The materials on this website are provided for general information only and should not be relied upon or used as the basis for making any decisions without consulting primary or more accurate, more complete or more timely sources of information. Any reliance on the materials on this website will be at your own risk. This website may contain certain historical information. Historical information is not current and is provided for your reference only. We reserve the right to modify the contents of this website at any time, but we have no obligation to update any information on the website. You agree that it is your responsibility to monitor changes to the website.</p>
            </div>
            <div className="mb-4">
                <header className="text-lg font-bold">Use of Materials From the Website</header>
                <p className="text">Except where explicitly stated otherwise, this website and all of its content (including but not limited to software, files, graphics and data) are the property of and owned by Chiranabin and/or its affiliates, suppliers or licensors and are protected by copyright, trademark and other laws of India and other countries. You may display and electronically copy, download and print hard-copy versions of the materials contained on the website for your personal and non-commercial use, provided that you do not modify or delete any copyright, trademark or other proprietary notice that appears on the materials you copy, download or print. When you display, copy, download or print any materials on or from the website, they are provided to you by Chiranabin and/or its affiliates, suppliers or licensors under a license that is revocable at will by Chiranabin. Chiranabin and/or its affiliates, suppliers or licensors retain full and complete title to the materials and to any and all of the associated intellectual property rights. Any other use of the materials on the website, including but not limited to the modification, distribution, transmission, performance, broadcast, reproduction, publication, licensing, reverse engineering, transfer or sale of, or the creation of derivative works from, any materials, information, software, products or services obtained from the website, without the prior written permission of Chiranabin, is expressly prohibited.</p>
            </div>
            <div className="mb-4">
                <header className="text-lg font-bold">Materials You Submit</header>
                <p className="text">The website may contain features and functionality permitting you to publish, upload, post, display or otherwise submit (collectively, “Publish”) certain information, comments and other content that may be viewed by us, the general public and other users of the website. You are responsible for any information, comments or other content Published by you or any person using your computer. You agree not to Publish any information, comments or other data that is or may reasonably be considered libellous, defamatory, obscene, threatening, invasive of privacy or publicity rights, infringing or misappropriating of intellectual property rights, abusive, illegal or otherwise objectionable, or which may constitute or encourage a criminal offense, violate the rights of any party or otherwise give rise to liability or violate any law, or consists of or contains software viruses, political campaigning, commercial solicitation, chain letters, mass mailings or any form of "spam." You may not use a false email address, impersonate any person or entity or otherwise mislead as to the origin of information, comments or other content Published by you. We reserve the right (but not the obligation) to remove or edit such content, but do not regularly review posted content provided. You may not use the website in any manner that could damage, disable, overburden or impair any Chiranabin server (including the servers of any Chiranabin’s third-party provider) or the network(s) connected to any Chiranabin server (including the servers of any Chiranabin’s third-party provider), or interfere with any other party's use and enjoyment of all or any portion of the website. You may not attempt to gain unauthorized access to any restricted web pages or any web pages requiring registration in order to view, through hacking, password mining or any other means. You may not obtain or attempt to obtain any materials or information through any means not intentionally made available through the website by Chiranabin. Any access or use of web pages requiring registration are subject to your registration on the site and is further governed by the Restricted Sites Terms and Conditions available at www.chiranabin.org.in</p>
            </div>
            <div className="mb-4">
                <header className="text-lg font-bold">Disclaimers</header>
                <p className="text">YOUR USE OF THIS WEBSITE IS AT YOUR OWN RISK. THE WEBSITE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. WE RESERVE THE RIGHT TO RESTRICT OR TERMINATE YOUR ACCESS TO THE WEBSITE OR ANY FEATURE OR ANY PART THEREOF AT ANY TIME. Chiranabin EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTIES THAT MATERIALS ON THE WEBSITE ARE NONINFRINGING; THAT ACCESS TO THE WEBSITE WILL BE UNINTERRUPTED OR ERROR-FREE; THAT THE WEBSITE OR ANY CONTENT SUBMITTED TO THE WEBSITE WILL BE SECURE; THAT THE WEBSITE OR THE SOFTWARE AND SERVERS THAT MAKE THE WEBSITE AVAILABLE WILL BE VIRUS-FREE; OR THAT INFORMATION ON THE WEBSITE WILL BE COMPLETE, ACCURATE OR TIMELY. IF YOU DOWNLOAD ANY MATERIALS FROM THIS WEBSITE, YOU DO SO AT YOUR OWN DISCRETION AND RISK. YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIALS. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM Chiranabin OR THROUGH OR FROM THE WEBSITE SHALL CREATE ANY WARRANTY OF ANY KIND. Chiranabin DOES NOT MAKE ANY WARRANTIES OR REPRESENTATIONS REGARDING ANY RESULTS OBTAINED BY YOU IN RELYING ON THE MATERIALS ON THIS WEBSITE OR THE USE OF THE MATERIALS ON THIS WEBSITE IN TERMS OF THEIR COMPLETENESS, CORRECTNESS, ACCURACY, ADEQUACY, USEFULNESS, TIMELINESS, RELIABILITY OR OTHERWISE. IN CERTAIN STATES, THE LAW MAY NOT PERMIT THE DISCLAIMER OF WARRANTIES, SO ALL OR PORTIONS OF THE ABOVE DISCLAIMER MAY NOT APPLY TO YOU.</p>
            </div>
        </div>
    )
}