import React from 'react';

export default function PrivacyPolicy() {
    return (
        <div className="flex text-center flex-col mt-2">
            <div className="mb-4">
                <h1 className="text-4xl mb-4 font-extrabold">Privacy Policy</h1>
                <p className="text">We at Chiranabin respect your concerns about privacy and value the relationship we have with you. We are committed to the ethical collection, retention and use of information that you provide to us about yourself (“Personal Information”) on this site www.Chiranabinindia.org (“Site”). This policy describes the types of personal information we collect, how we may use that information and with whom we may share it when you visit our site or use our services (collectively the “Services”). Our Privacy Policy also describes the measures we take to protect the security of the information. In addition, we describe the choices you can make about how we use the information you provide to us. We also tell you how you can reach us to update your contact information, remove your name from our mailing lists, or answer any questions you may have about our privacy practices. We maintain full confidentiality of all donors and contributors on our mailing and email lists, which will neither be sold to nor exchanged with any other organization or commercial enterprise, and we honour donors’ opt-out choices in our mail, email, phone and other solicitations.</p>
            </div>
            <div className="mb-4">
                <header className="text-lg font-bold">Information We Collect and How We Use It</header>
                <p className="text">We may collect information about you directly from you and from third parties, as well as automatically through your use of our Site or Services to extend services like for our internal purposes, processing of your donations, providing receipts and tax exemption certificates, sending regular updates about the work we do for children, respond to your queries and apprising you of the new opportunities to help deprived and marginalized children of India in a better way. We seek your personal information when you make a donation, request a communication from us, register for an on-ground event, pledge support to our work and campaigns and apply for working or volunteering with Chiranabin. This information may be sought over the phone, through the website, via email or by the means of face-to-face interaction. You may choose to provide personal information either by phone, mail or on our Site. Certain areas and features of our Site and Services may require registration. To register, you must provide your name, address, email address, login and password. We may also request from you or allow you to submit additional optional information, depending on the type of communication or transaction the personal information we collect may include, but is not limited to, your name, postal address, date of birth, PIN code, telephone numbers, mobile phone numbers, your organization’s name, email addresses, credit/debit card information, bank information or billing information. Irrespective of the mode in which we receive your personal information, we make all earnest attempts to honour your privacy.</p>
            </div>
            <div className="mb-4">
                <header className="text-lg font-bold">Email Communications</header>
                <p className="text">When you ask us to send you email such as a free email newsletter, you may provide us with certain information such as your email address so we can fulfil your request. You may choose to provide additional information as well, such as your postal address and phone number.</p>
            </div>
            <div className="mb-4">
                <header className="text-lg font-bold">Donations</header>
                <p className="text">When you make a donation through our Site, we may ask you to submit certain personal information (such as credit card information) so we can process your donation. We also maintain your contact information in our records so we can contact you to provide Chiranabin’s program information and information on additional giving opportunities.</p>
            </div>
            <div className="mb-4">
                <header className="text-lg font-bold">Refunds and Cancellations</header>
                <p className="text">We take the utmost care to process donations as per the instructions given by our donors, online and offline. However, in case of an unlikely event of an erroneous donation, we will respond to the donor within 7 working days of receiving a valid request for refund from the donor. The timely refund of the donation will depend upon the type of credit card/banking instrument used during the transaction. The donor will have to send us a written request for a refund within 2 days of making the donation along with- Proof of the deduction of the donation amount. In cases where the donation receipt has already been issued to the donor, the donor will have to return the original receipt to us at our office address. If the tax exemption certificate is already issued, then we are sorry but we will not be able to refund the donation. However, in case of a valid refund request due to any error on our part, we will refund the donation and bear the costs of the same. If the donor doesn’t write within two days, then refund is not possible.</p>
            </div>
            <div className="mb-4">
                <header className="text-lg font-bold">Questionnaires and Surveys</header>
                <p className="text">We occasionally may ask visitors to our Site to complete online surveys and opinion polls about their activities, attitudes and interests. These surveys help us understand the needs of our visitors. We do not keep any personal information about you in connection with your participation in a Site survey unless you specifically agree to provide this information.</p>
            </div>
            <div className="mb-4">
                <header className="text-lg font-bold">Cookies and Web Beacons</header>
                <p className="text">We use cookies and other tracking mechanisms to track information about your use of our Site or Services. We may combine this information with other personal information we collect from you. Cookies are pieces of electronic information which will be sent by Chiranabin for record-keeping purposes when you log onto our web site. These will be placed in your computer's hard disk and enable us to recognise you as a user when you next visit. Some cookies allow us to make it easier for you to navigate our Site and Services, while others are used to enable a faster login process or to allow us to track your activities at our Site and Service. There are two types of cookies: session and persistent cookies. Session Cookies - Session cookies exist only during an online session. They disappear from your computer when you close your browser or turn off your computer. We use session cookies to allow our systems to uniquely identify you during a session or while you are logged in to the Site. This allows us to process your online transactions and requests and verify your identity after you have logged in and as you move through our Site. Persistent cookies - Persistent cookies remain on your computer after you have closed your browser or turned off your computer. We use persistent cookies to track aggregate and statistical information about user activity.</p>
            </div>
            
        </div>
    )
}